### ISSUE TITLE
Help to speed up the code

### ISSUE THREAD

**Issue by shreyask3107** [denisyarats/pytorch_sac#4]
Hi, the code currently takes around 15hours for a million epochs, could you guide me into increasing this speed and not deteriorating the performance. As the compute required for the code is pretty less, i would like to utilize them to speed up. Thanks!

**Comment by denisyarats** [comment]
Hi, I'm currently working on speeding this code up. If you look at the ddpg branch, there is experimental implementations of SAC / DDPG what work much faster, but I haven't fully tested them yet.

**Comment by shreyask3107** [comment]
Thank You for the update, that would help me a lot.

**Comment by shreyask3107** [comment]
Could you give me an idea of how much faster this is expected to be from the earlier code?

**Comment by denisyarats** [comment]
Hi, it should be way faster, on my machine 1M of environment steps takes less than 2 hours on a single GPU. So most of the tasks from DM control should be solved in 2 hours or so.

**Comment by shreyask3107** [comment]
Wow, Thanks!
